version: '3.8'

services:
  # Base de datos local exclusiva para las pruebas de productos
  product-mysql:
    image: mysql:8.0
    container_name: product_mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - product_db_data:/var/lib/mysql

  # Microservicio de Productos en Python
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eval3_product_backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB_HOST=product-mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - product-mysql

volumes:
  product_db_data: